---
deployment:
 tasks:
 - export DEPLOY_PATH=/home/c2484026c/vtc_pro/
 - echo "Starting deployment..."
 - /bin/cp -R . $DEPLOY_PATH
 - cd $DEPLOY_PATH
 - composer install --no-dev --prefer-dist --optimize-autoloader
 - php artisan migrate --force
 - php artisan optimize:clear
 - echo "Deployment completed successfully."
